# Generated by Django 5.2.7 on 2025-10-27 23:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("air_quality", "0001_initial"),
        ("django_ai_blocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(db_index=True, verbose_name="triggered at"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="measurement value",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "measurement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="air_quality.measurement",
                        verbose_name="measurement",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="air_quality.sitealertrule",
                        verbose_name="alert rule",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="django_ai_blocks.workflow",
                    ),
                ),
                (
                    "workflow_state",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="django_ai_blocks.state",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site alert",
                "verbose_name_plural": "Site alerts",
                "ordering": ("-triggered_at", "-pk"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rule", "measurement"),
                        name="unique_alert_per_rule_measurement",
                    )
                ],
            },
        ),
    ]
