# Generated by Django 5.2.7 on 2025-10-28 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockcolumnconfig',
            options={'verbose_name': 'table setting', 'verbose_name_plural': 'table settings'},
        ),
        migrations.AlterModelOptions(
            name='blockfilterconfig',
            options={'verbose_name': 'block filter', 'verbose_name_plural': 'block filters'},
        ),
        migrations.AlterModelOptions(
            name='layoutfilterconfig',
            options={'verbose_name': 'layout filter', 'verbose_name_plural': 'layout filters'},
        ),
        migrations.AlterModelOptions(
            name='pivotconfig',
            options={'verbose_name': 'pivot setting', 'verbose_name_plural': 'pivot settings'},
        ),
    ]
